# Generated by Django 4.1 on 2022-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('cnum', models.IntegerField(max_length=14)),
                ('pstad', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('payment', models.BooleanField()),
            ],
        ),
    ]
