# Generated by Django 4.1 on 2022-11-26 11:36

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.ConfirmOrderImagePath)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
